name: build-and-deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write # required for official Pages deploy action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # -------- Quarto blog (/blog) --------
      - uses: quarto-dev/quarto-actions/setup@v2
      - run: quarto render src/blog # _quarto.yml handles output‑dir

      # -------- Quarto → Docusaurus (/md) --------
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Install JS deps
        run: |
          cd docusaurus
          npm ci                                # or pnpm/yarn
      - name: Render Quarto docs
        run: quarto render src/md # writes to docusaurus/docs
      - name: Build Docusaurus site
        run: |
          cd docusaurus
          npm run build                        # outputs to docusaurus/build
          rsync -a --delete build/ ../docs/md

      # -------- Optional extras --------
      - run: marimo convert src/nb --out docs/nb || true
      - run: ./build_shiny_wasm.sh && cp -r shiny_build docs/app || true

      # -------- Package for Pages --------
      - run: touch docs/.nojekyll
      - uses: actions/upload-pages-artifact@v3
        with: { path: docs }

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - id: deploy
        uses: actions/deploy-pages@v4 # official deploy action :contentReference[oaicite:3]{index=3}
